# Generated by Django 6.0.4 on 2026-04-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_seed_device_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NamePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pool nomi')),
                ('category', models.CharField(choices=[('group', 'Guruh'), ('channel', 'Kanal'), ('any', 'Har qanday')], default='any', max_length=20, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_pools', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Nom pool',
                'verbose_name_plural': "Nom pool'lar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('create_groups', 'Guruh yaratish'), ('create_channels', 'Kanal yaratish'), ('join_channel', "Kanalga qo'shilish"), ('boost_views', 'View oshirish'), ('vote_poll', 'Ovoz berish'), ('press_start', 'Botga /start'), ('run_script', 'Skript ishga tushirish')], max_length=32, verbose_name='Turi')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Parametrlar')),
                ('status', models.CharField(choices=[('pending', 'Kutmoqda'), ('running', 'Ishlamoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xato'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat')),
                ('total', models.IntegerField(default=0, verbose_name='Jami')),
                ('done', models.IntegerField(default=0, verbose_name='Bajarilgan')),
                ('success_count', models.IntegerField(default=0, verbose_name='Muvaffaqiyat')),
                ('error_count', models.IntegerField(default=0, verbose_name='Xatolar')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='Statistika')),
                ('error', models.TextField(blank=True, default='', verbose_name='Umumiy xato')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name="Bekor qilish so'raldi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RandomName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Matn')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='jobs.namepool', verbose_name='Pool')),
            ],
            options={
                'verbose_name': 'Random nom',
                'verbose_name_plural': 'Random nomlar',
                'ordering': ['id'],
                'unique_together': {('pool', 'text')},
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', "Ma'lumot"), ('success', 'Muvaffaqiyat'), ('warning', 'Ogohlantirish'), ('error', 'Xato')], default='info', max_length=16, verbose_name='Daraja')),
                ('step', models.CharField(blank=True, default='', max_length=64, verbose_name='Qadam')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('telegram_error', models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram xato kodi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_events', to='accounts.account', verbose_name='Akkaunt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Vazifa hodisasi',
                'verbose_name_plural': 'Vazifa hodisalari',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['task', 'id'], name='jobs_taskev_task_id_4524d8_idx'), models.Index(fields=['task', 'level'], name='jobs_taskev_task_id_e1a953_idx')],
            },
        ),
    ]
