# Generated by Django 6.0.4 on 2026-04-24 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_task_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('code', models.TextField(verbose_name='Kod (Python async)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_templates', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
            ],
            options={
                'verbose_name': 'Skript shabloni',
                'verbose_name_plural': 'Skript shablonlari',
                'ordering': ['-updated_at'],
            },
        ),
    ]
