# Generated by Django 6.0.4 on 2026-04-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_scripttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring_cron',
            field=models.CharField(blank=True, default='', help_text="Masalan: '*/30 * * * *' har 30 daqiqada. Bo'sh — bir martalik.", max_length=100, verbose_name='Cron (takroriy)'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='jobs.task', verbose_name='Takroriy ota-task'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="Bo'sh qoldirilsa darhol ishga tushadi", null=True, verbose_name='Belgilangan vaqt'),
        ),
    ]
