# Generated by Django 6.0.4 on 2026-04-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_task_recurring_cron_task_recurring_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('create_groups', 'Guruh yaratish'), ('create_channels', 'Kanal yaratish'), ('join_channel', "Kanalga qo'shilish"), ('boost_views', 'View oshirish'), ('react_to_post', "Reaksiya qo'yish"), ('vote_poll', 'Ovoz berish'), ('press_start', 'Botga /start'), ('run_script', 'Skript ishga tushirish'), ('account_warming', 'Akkaunt warming')], max_length=32, verbose_name='Turi'),
        ),
    ]
