# Generated by Django 6.0.4 on 2026-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_task_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('create_groups', 'Guruh yaratish'), ('create_channels', 'Kanal yaratish'), ('join_channel', "Kanalga qo'shilish"), ('leave_groups', 'Guruhlardan chiqish (admin emas)'), ('leave_channels', 'Kanallardan chiqish (admin emas)'), ('send_message', 'Xabar yuborish'), ('update_profile', 'Profilni yangilash'), ('view_stories', "Stories ko'rish"), ('mark_all_read', "Hammasini o'qilgan deb belgilash"), ('set_2fa_password', "2FA parolni o'rnatish"), ('boost_views', 'View oshirish'), ('react_to_post', "Reaksiya qo'yish"), ('vote_poll', 'Ovoz berish'), ('press_start', 'Botga /start'), ('run_script', 'Skript ishga tushirish'), ('account_warming', 'Akkaunt warming')], max_length=32, verbose_name='Turi'),
        ),
    ]
