# Generated by Django 6.0.4 on 2026-05-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_task_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pause_requested',
            field=models.BooleanField(default=False, verbose_name="Pauza so'raldi"),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutmoqda'), ('running', 'Ishlamoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xato'), ('cancelled', 'Bekor qilindi'), ('paused', 'Pauza')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.CreateModel(
            name='TaskCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='Kalit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='jobs.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Vazifa checkpoint',
                'verbose_name_plural': 'Vazifa checkpointlari',
                'indexes': [models.Index(fields=['task', 'key'], name='jobs_taskch_task_id_0752ef_idx')],
                'unique_together': {('task', 'key')},
            },
        ),
    ]
