# Generated by Django 6.0.4 on 2026-04-11 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True, verbose_name='Setting Name')),
                ('device_model', models.CharField(default='Samsung S27 ultra', max_length=100)),
                ('system_version', models.CharField(default='Android 15', max_length=50)),
                ('app_version', models.CharField(default='12.6.4', max_length=50)),
                ('lang_code', models.CharField(default='uz', max_length=10)),
                ('system_lang_code', models.CharField(default='uz', max_length=10)),
            ],
            options={
                'verbose_name': 'Device Setting',
                'verbose_name_plural': 'Device Settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram User ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('two_fa_password', models.CharField(blank=True, help_text='Optional', max_length=255, null=True, verbose_name='2FA Password')),
                ('session_string', models.TextField(blank=True, null=True, verbose_name='Telethon Session String')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_spam', models.BooleanField(default=False, verbose_name='Is Spam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('tags', models.ManyToManyField(blank=True, related_name='accounts', to='accounts.tag', verbose_name='Tags')),
            ],
        ),
    ]
