# Generated by Django 6.0.4 on 2026-04-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Avatar URL Path'),
        ),
    ]
