# Generated by Django 6.0.4 on 2026-04-24 10:15

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_tag_options_tag_owner_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='session_string',
            field=accounts.fields.EncryptedTextField(blank=True, null=True, verbose_name='Telethon Session String'),
        ),
        migrations.AlterField(
            model_name='account',
            name='two_fa_password',
            field=accounts.fields.EncryptedTextField(blank=True, help_text='Optional', null=True, verbose_name='2FA Password'),
        ),
    ]
