# Generated by Django 6.0.4 on 2026-04-24 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_session_string_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('proxy_type', models.CharField(choices=[('socks5', 'SOCKS5'), ('mtproto', 'MTProxy')], default='socks5', max_length=10, verbose_name='Turi')),
                ('host', models.CharField(max_length=255, verbose_name='Host / IP')),
                ('port', models.PositiveIntegerField(verbose_name='Port')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Login')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='Parol')),
                ('secret', models.CharField(blank=True, default='', max_length=255, verbose_name='MTProxy secret (faqat mtproto)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tekshiruv')),
                ('last_check_ok', models.BooleanField(blank=True, null=True, verbose_name='Oxirgi tekshiruv natijasi')),
                ('last_check_error', models.TextField(blank=True, default='', verbose_name='Oxirgi xato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': "Proxy'lar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='proxy',
            field=models.ForeignKey(blank=True, help_text="Bo'sh qoldirilsa to'g'ridan-to'g'ri ulanish", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.proxy', verbose_name='Proxy'),
        ),
    ]
