# Generated by Django 6.0.4 on 2026-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_proxy_account_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='daily_op_limit',
            field=models.PositiveIntegerField(default=200, help_text='0 = cheksiz', verbose_name='Kunlik limit'),
        ),
        migrations.AddField(
            model_name='account',
            name='quota_window_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Bugun bajarilgan'),
        ),
        migrations.AddField(
            model_name='account',
            name='quota_window_start',
            field=models.DateField(blank=True, null=True, verbose_name='Byudjet oynasi boshlandi'),
        ),
    ]
