# Generated by Django 6.0.4 on 2026-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_daily_op_limit_account_quota_window_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='flood_wait_count_24h',
            field=models.PositiveIntegerField(default=0, verbose_name="So'nggi 24h FloodWait soni"),
        ),
        migrations.AddField(
            model_name='account',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=100, help_text='0–100. Quyi → akkaunt risk ostida.', verbose_name="Sog'lik balli"),
        ),
        migrations.AddField(
            model_name='account',
            name='health_score_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sog'lik baholangan vaqt"),
        ),
        migrations.AddField(
            model_name='account',
            name='last_successful_op_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi muvaffaqiyatli operatsiya'),
        ),
    ]
