"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import base64
import hashlib
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=()):
    raw = os.environ.get(name, '')
    if not raw:
        return list(default)
    return [x.strip() for x in raw.split(',') if x.strip()]


TELEGRAM_API_ID = os.environ.get("API_ID", "")
TELEGRAM_API_HASH = os.environ.get("API_HASH", "")


# ---------------------------------------------------------------------------
# Secrets and debug
# ---------------------------------------------------------------------------

SECRET_KEY = os.environ.get('SECRET_KEY') or ''
if not SECRET_KEY:
    # Running without a SECRET_KEY is unsafe. Crash loudly unless we're in a
    # context where it's obvious (e.g., `manage.py help`).
    if 'runserver' in sys.argv or 'migrate' in sys.argv or 'run_worker' in sys.argv:
        raise RuntimeError(
            "SECRET_KEY is not set. Add it to .env "
            "(run `python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\"` "
            "to generate one)."
        )
    SECRET_KEY = 'unsafe-placeholder-please-set-SECRET_KEY-in-env'

DEBUG = _env_bool('DEBUG', default=False)

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    # Unfold MUST come before django.contrib.admin so its templates win.
    # `unfold.contrib.import_export` rewires the import-export form widgets
    # to match the dashboard's look — drop it if you remove that integration.
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'import_export',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap5',

    # Local apps
    'accounts',
    'groups',
    'channels',
    'jobs',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ---------------------------------------------------------------------------
# Unfold admin theme
# https://unfoldadmin.com/docs/configuration/settings/
# ---------------------------------------------------------------------------

UNFOLD = {
    "SITE_TITLE": "Userbot Manager — Admin",
    "SITE_HEADER": "Userbot Manager",
    "SITE_SUBHEADER": "Multi-tenant Telegram boshqaruvi",
    "SITE_URL": "/",
    "SITE_SYMBOL": "rocket_launch",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": None,  # respect the user's OS preference (light/dark)
    "COLORS": {
        "primary": {
            "50": "240 249 255", "100": "224 242 254", "200": "186 230 253",
            "300": "125 211 252", "400": "56 189 248", "500": "14 165 233",
            "600": "2 132 199", "700": "3 105 161", "800": "7 89 133",
            "900": "12 74 110", "950": "8 47 73",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Akkauntlar",
                "separator": True,
                "items": [
                    {"title": "Akkauntlar", "icon": "person", "link": "/admin/accounts/account/"},
                    {"title": "Tag'lar", "icon": "label", "link": "/admin/accounts/tag/"},
                    {"title": "Proxy'lar", "icon": "vpn_key", "link": "/admin/accounts/proxy/"},
                    {"title": "Device sozlamalari", "icon": "devices", "link": "/admin/accounts/devicesetting/"},
                ],
            },
            {
                "title": "Telegram obyektlari",
                "separator": True,
                "items": [
                    {"title": "Guruhlar", "icon": "group", "link": "/admin/groups/group/"},
                    {"title": "Kanallar", "icon": "campaign", "link": "/admin/channels/channel/"},
                ],
            },
            {
                "title": "Vazifalar",
                "separator": True,
                "items": [
                    {"title": "Tasks", "icon": "task", "link": "/admin/jobs/task/"},
                    {"title": "Hodisalar", "icon": "history", "link": "/admin/jobs/taskevent/"},
                    {"title": "Nom pool'lari", "icon": "collections_bookmark", "link": "/admin/jobs/namepool/"},
                    {"title": "Skript shabloni", "icon": "code", "link": "/admin/jobs/scripttemplate/"},
                ],
            },
            {
                "title": "Foydalanuvchilar",
                "separator": True,
                "items": [
                    {"title": "User'lar", "icon": "manage_accounts", "link": "/admin/auth/user/"},
                    {"title": "Group'lar (auth)", "icon": "groups", "link": "/admin/auth/group/"},
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files in production. No-op when DEBUG=True
    # (Django's runserver still serves them via APP_DIRS).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_alerts',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DB_ENGINE: 'sqlite' (default for local dev) or 'postgres' (recommended for production).
DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite').strip().lower()

if DB_ENGINE == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':     os.environ.get('POSTGRES_DB', 'userbots'),
            'USER':     os.environ.get('POSTGRES_USER', 'userbots'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST':     os.environ.get('POSTGRES_HOST', 'db'),
            'PORT':     os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz-uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: gzip + cache-busting hashed filenames for production.
# Falls back to non-hashed in DEBUG so runserver still finds files.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'
                   if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = '/accounts/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# ---------------------------------------------------------------------------
# DB field encryption (Account.session_string, Account.two_fa_password)
# ---------------------------------------------------------------------------

def _derive_fernet_key(secret):
    """Derive a Fernet-compatible key from SECRET_KEY when DB_ENCRYPTION_KEY isn't set."""
    digest = hashlib.pbkdf2_hmac('sha256', secret.encode(), b'userbot-manager-db-v1', 100_000)
    return base64.urlsafe_b64encode(digest).decode()


DB_ENCRYPTION_KEY = os.environ.get('DB_ENCRYPTION_KEY') or _derive_fernet_key(SECRET_KEY)


# ---------------------------------------------------------------------------
# Production security flags
# Enabled only when DEBUG is off so local dev (HTTP) isn't broken.
# ---------------------------------------------------------------------------

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'

    # HSTS: 1 year (browsers cache the HTTPS-only flag this long). PRELOAD
    # stays False — submitting to hstspreload.org locks you in permanently.
    # security.W021 warns about PRELOAD=False; we silence it below since
    # opting out of preload is a deliberate, documented choice.
    SECURE_HSTS_SECONDS = 31_536_000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False
    SILENCED_SYSTEM_CHECKS = ['security.W021']

    # Reverse-proxy CSRF origin trust. The host nginx sets X-Forwarded-Proto
    # so the form-submit Origin matches https://<host>; explicit list also
    # documents which hosts are expected to POST to us.
    CSRF_TRUSTED_ORIGINS = [
        f"https://{h}" for h in ALLOWED_HOSTS
        if h not in ('localhost', '127.0.0.1', '*')
    ]

    # Only redirect to HTTPS when a reverse proxy is in front and sets the
    # X-Forwarded-Proto header. Don't force redirects from the app itself
    # unless you know Django is the edge — you'll get a redirect loop.
    if _env_bool('SECURE_BEHIND_PROXY', default=False):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        SECURE_SSL_REDIRECT = True
        # /healthz is hit over plain HTTP from inside the docker network
        # (host nginx active probe + Docker healthcheck). Without this
        # exemption Django would 301 it to HTTPS and the probe would fail.
        SECURE_REDIRECT_EXEMPT = [r'^healthz$']


# ---------------------------------------------------------------------------
# Logging — rotating files under logs/ + console pass-through.
# Volume-mounted in docker-compose so files survive container rebuilds.
# ---------------------------------------------------------------------------

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'error.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': os.environ.get('LOG_LEVEL', 'INFO').upper(),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'jobs.runners': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
