# Generated by Django 6.0.4 on 2026-04-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ochilgan sanasi')),
                ('telegram_id', models.BigIntegerField(verbose_name='Guruh ID si')),
                ('invite_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Invite link')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.account', verbose_name='Egasi (Account)')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
    ]
