# Generated by Django 6.0.4 on 2026-05-06 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', help_text="@BotFather'da yangi bot yaratib, tokenini yopishtiring", max_length=128, verbose_name='Bot token')),
                ('chat_id', models.CharField(blank=True, default='', help_text='Bildirishnoma yuboriladigan chat ID (foydalanuvchi yoki guruh)', max_length=64, verbose_name='Chat ID')),
                ('events', models.JSONField(blank=True, default=list, verbose_name='Yoqilgan eventlar')),
                ('enabled', models.BooleanField(default=True, verbose_name='Yoqilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma sozlamasi',
                'verbose_name_plural': 'Bildirishnoma sozlamalari',
            },
        ),
    ]
